GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoibXViYXJhayIsImlhdCI6MTYwMjY3MjY5OCwiZXhwIjoxNjAyNjcyNzEzfQ.YaurmCA-T8BNDNKHKWr9Mnj4qDxz8P5FtasSMNkVpUU

###



GET http://localhost:4000/getData
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoibXViYXJhayIsImlhdCI6MTYwMjY4NDA4NSwiZXhwIjoxNjAyNjg0MTAwfQ.My0N7em8zJmzIAQIFbcO0yGar8u4VjXIeEOwAupTb-U



###


DELETE http://localhost:4000/logout
Content-Type: application/json

{
    "token" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoibXViYXJhayIsImlhdCI6MTYwMjU2ODk5M30._Xv2se2gb-lOoK7SxDqTDxlu74WCYrjlsprq8F2CrKE"
}

###

POST http://localhost:4000/token
Content-Type: application/json

{
    "token" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoibXViYXJhayIsImlhdCI6MTYwMjU2ODk5M30._Xv2se2gb-lOoK7SxDqTDxlu74WCYrjlsprq8F2CrKE"
}



###

POST http://localhost:4000/login
Content-Type: application/json

{
    "username" : "mubarak"
}